### ISSUE TITLE
Crear repositorio y equipo de trabajo en github.

### ISSUE THREAD

**Issue by Equipo9-G10** [Equipo9-G10/sima#4]
1. Crear repositorio y equipo de trabajo en github.
2. Crear proyecto y crear el tablero el seguimiento de tareas para los sprints e implementación del sistema.
3. Asignar permisos a los intregrantes del equipo para que puedan interactuar y realizar aportes correspondientes del proyecto según sus roles.

**Comment by jalvarezy** [comment]
Crear repositorio y equipo de trabajo en github.
Se crea correo [equipomisiontic@gmail.com](mailto:equipomisiontic@gmail.com), el cual será utilizado como correo padre del repositorio del proyecto, se crea cuenta en github con nombre de usuario: Equipo9-G10 y, se crea el repositorio sima (Sistema de mantenimiento Automotríz).

Crear proyecto y crear el tablero el seguimiento de tareas para los sprints e implementación del sistema.
Se crea proyecto: @Equipo9-G10_simaBoard con su respectivo tablero para el seguimiento de tareas de los sprints e implementación del sistema.

Asignar permisos a los intregrantes del equipo para que puedan interactuar y realizar aportes correspondientes del proyecto según sus roles.
Se comparte repositorio del proyecto a los integrantes del equipo de trabajo y se le asignan los respectivos permisos a los usuarios.
